CREATE DEFINER=`moustafa`@`%` PROCEDURE `reset_quote_adjust`( IN switch INT, IN amp INT)
BEGIN
TRUNCATE TABLE QUOTE_ADJUST;
INSERT INTO QUOTE_ADJUST (INSTRUMENT_ID) (SELECT INSTRUMENT_ID FROM INSTRUMENT);
UPDATE QUOTE_ADJUST SET AMPLITUDE= amp /*(RAND()+.5)*/ WHERE INSTRUMENT_ID IN (SELECT INSTRUMENT_ID FROM INSTRUMENT);
UPDATE QUOTE_ADJUST SET switchpoint= switch /*ROUND((RAND()+.5)*400)*/ WHERE INSTRUMENT_ID IN (SELECT INSTRUMENT_ID FROM INSTRUMENT);
END