DELIMITER $$
CREATE DEFINER=`moustafa`@`%` PROCEDURE `reset_quote_adjust`(  )
BEGIN
update QUOTE_ADJUST set AMPLITUDE=(RAND()+.5) WHERE INSTRUMENT_ID IN (SELECT INSTRUMENT_ID FROM INSTRUMENT);
update QUOTE_ADJUST set switchpoint=ROUND((RAND()+.5)*400) WHERE INSTRUMENT_ID IN (SELECT INSTRUMENT_ID FROM INSTRUMENT);
END$$
DELIMITER ;
