DELIMITER $$
CREATE DEFINER=`moustafa`@`%` PROCEDURE `reset_quote_adjust`(  )
BEGIN
TRUNCATE TABLE QUOTE_ADJUST;
INSERT INTO QUOTE_ADJUST(INSTRUMENT_ID) SELECT INSTRUMENT_ID FROM INSTRUMENT;
update QUOTE_ADJUST set AMPLITUDE= 2 /*(RAND()+.5)*/ WHERE INSTRUMENT_ID IN (SELECT INSTRUMENT_ID FROM INSTRUMENT);
update QUOTE_ADJUST set switchpoint= 300 /*ROUND((RAND()+.5)*400)*/ WHERE INSTRUMENT_ID IN (SELECT INSTRUMENT_ID FROM INSTRUMENT);
END$$
DELIMITER ;
